### ISSUE TITLE
Stmt.BindBytes binds text instead of a blob

### ISSUE THREAD

**Issue by zombiezen** [crawshaw/sqlite#94]
[`Stmt.BindBytes`](https://pkg.go.dev/crawshaw.io/sqlite?tab=doc#Stmt.BindBytes) calls [`transient_bind_text`](https://github.com/crawshaw/sqlite/blob/6c1d4ad4ed9d0acc0ca4b99dd67c5c14d488633c/sqlite.go#L51-L53), which ends up calling `sqlite3_bind_text` rather than `sqlite3_bind_blob`. This means that it is impossible to safely pass in a blob with NUL bytes into this package and it causes subtle, hard-to-diagnose type issues.

This was introduced intentionally in 4b840ed2d80e42d6abb584cebba494ed8d2d1cd5, but I think the behavior is surprising.

**Comment by anacrolix** [comment]
If the field genuinely contains NUL bytes, then would be best practice to use BLOB regardless?

**Comment by zombiezen** [comment]
I'm not sure I understand the question, but I agree that using `BLOB` is correct in circumstances where the values can contain NUL bytes.

**Comment by creachadair** [comment]
I hit the same issue. I'm writing to a column that is already a `BLOB`, so the issue is not the column type. As far as I can see the only workaround to write a blob with the existing API is to explicitly run a transaction around creating the zero blob and then writing into it. 

I don't think this behaviour really makes sense for `BindBytes`, but if indeed it is working-as-intended, would you be willing to entertain a PR to make the documentation more explicit?

**Comment by anacrolix** [comment]
Working around this seems to have a performance impact: I think SQLite isn't able to do certain optimizations/caching through `cast(a as blob)`.
